### ISSUE TITLE
I have a question about your intersect function.

### ISSUE THREAD

**Issue by irisqp** [guillelopez/python-traffic-counter-with-yolo-and-sort#1]
hello, @guillelopez Thanks for your work, It's really cool.
I read your code , and I found a function you used to judge whether line segments AB and CD intersect. It's pretty hard for me to understand how it works. here are the function:
# Return true if line segments AB and CD intersect
def intersect(A,B,C,D):
	return ccw(A,C,D) != ccw(B,C,D) and ccw(A,B,C) != ccw(A,B,D)

def ccw(A,B,C):
	return (C[1]-A[1]) * (B[0]-A[0]) > (B[1]-A[1]) * (C[0]-A[0])
 could you please show me some explanation for this algorithm. Thank you very much!

**Comment by guillelopez** [comment]
Hi, you can find an explanation here: https://bryceboe.com/2006/10/23/line-segment-intersection-algorithm/

**Comment by irisqp** [comment]
> 
> 
> Hi, you can find an explanation here: https://bryceboe.com/2006/10/23/line-segment-intersection-algorithm/

Thanks a lot!
