### ISSUE TITLE
storing objects by id

### ISSUE THREAD

**Issue by alexmihalyk23** [guillelopez/python-traffic-counter-with-yolo-and-sort#12]
Hello, how to storing object by id so that when crossing the object a second time the counter is not added in this code(sorry for my english):

```
if indexIDs[i] in previous:
    previous_box = previous[indexIDs[i]]
    (x2, y2) = (int(previous_box[0]), int(previous_box[1]))
    (w2, h2) = (int(previous_box[2]), int(previous_box[3]))
    p0 = (int(x + (w-x)/2), int(y + (h-y)/2))
    p1 = (int(x2 + (w2-x2)/2), int(y2 + (h2-y2)/2))
    cv2.line(frame, p0, p1, color, 1) 
    if (intersect(p0, p1, line[0], line[1])) and (LABELS[classIDs[i]] == "car"):
        counter += 1

**Comment by bamwani** [comment]
You can create a list to cross_check, add the indexID to that list if it crosses the line, also, add an if condition to check if that indexID is present in our cross_check list.

```
if intersect(p0, p1, line1[0], line1[1]) and indexIDs[i] not in cross_check:
                                counter1 += 1
                                cross_check.append(indexIDs[i])
```

you can check my repo for any code help. 
https://github.com/bamwani/car-counting-and-speed-estimation-yolo-sort-python

**Comment by alexmihalyk23** [comment]
> Вы можете создать список для cross_check, добавить indexID в этот список, если он пересекает линию, а также добавить условие if, чтобы проверить, присутствует ли этот indexID в нашем списке cross_check.
> 
> ```
> cross_check = [ ]
> if intersect(p0, p1, line1[0], line1[1]) and indexIDs[i] not in cross_check:
>                                 counter1 += 1
>                                 cross_check.append(indexIDs[i])
> ```
> 
> Вы можете проверить мой репозиторий для любой помощи кода.
> https://github.com/bamwani/car-counting-and-speed-estimation-yolo-sort-python


thank you very much. You helped me a lot

**Comment by alexmihalyk23** [comment]
> You can create a list to cross_check, add the indexID to that list if it crosses the line, also, add an if condition to check if that indexID is present in our cross_check list.
> 
> ```
> cross_check = [ ]
> if intersect(p0, p1, line1[0], line1[1]) and indexIDs[i] not in cross_check:
>                                 counter1 += 1
>                                 cross_check.append(indexIDs[i])
> ```
> 
> you can check my repo for any code help.
> https://github.com/bamwani/car-counting-and-speed-estimation-yolo-sort-python


Thank you very much.
