### ISSUE TITLE
how can i use GPU to run this project for reduce time?

### ISSUE THREAD

**Issue by clemente620** [guillelopez/python-traffic-counter-with-yolo-and-sort#3]
thanks

**Comment by guillelopez** [comment]
I am not an expert. But I guess you should explore if there is a OpenCV version optimized for GPU and also for YOLO.

**Comment by clemente620** [comment]
yes i have a gpu station but i don't know how to do use your code with gpu


------------------ 原始邮件 ------------------
发件人: "Alejandro"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 凌晨1:50
收件人: "guillelopez/python-traffic-counter-with-yolo-and-sort"<python-traffic-counter-with-yolo-and-sort@noreply.github.com>;
抄送: "Clemente"<330841399@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [guillelopez/python-traffic-counter-with-yolo-and-sort] how can iuse GPU to run this project for reduce time? (#3)




You must use CUDA enabled GPU and have a working version of CUDA installed.
