### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by bpogorelc** [guillelopez/python-traffic-counter-with-yolo-and-sort#4]
Thank you for sharing this great project! However, using many videos I get an error "IndexError: too many indices for array". It works without issues using the video "highway.mp4" attached to the repository. It also works OK using one of my videos of the traffic but it throws an error with the rest, even though they are all recorded with the same camera and the same codec (h.264).

The complete error is the following:
(py370) user@machine:~$ python main.py --input input/ch02_20190325085127.avi --output output/ch02_20190325085127_out.avi --yolo yolo-coco
[INFO] loading YOLO from disk...
[INFO] 54420 total frames in video
[INFO] single frame took 0.7069 seconds
[INFO] estimated total time to finish: 38470.8409
Traceback (most recent call last):
  File "main.py", line 162, in <module>
    tracks = tracker.update(dets)
  File "/data/home/adminlinux/vehicleCounting/python-traffic-counter-with-yolo-and-sort/sort.py", line 203, in update
    trk.update(dets[d,:][0])
IndexError: too many indices for array

The error occurs with each video at the different frame. For example, using my first video only 230 frames are processed and then the error is thrown, the second video processes 800 frames, the third video over 3000 frames and so on, before the error is thrown. I have a hypothesis that the error occurs if in the first few seconds vehicles are detected but very few vehicles cross the detection line. Even though we want to count the vehicles in a video that can be 30 or 60 minutes long, the task is already terminated after processing a few seconds of the video, which is very problematic. I would appreciate a lot if you could help me resolving this issue.

I am using Ubuntu 16.04.6 LTS and Python 3.7.0 (default, Oct  9 2018, 10:31:47), [GCC 7.3.0] :: Anaconda, Inc. on linux

Here is the list of packages installed by pip
(py370) user@machine:~$ pip freeze
certifi==2019.3.9
cycler==0.10.0
filterpy==1.4.5
imutils==0.5.2
kiwisolver==1.0.1
llvmlite==0.28.0
matplotlib==3.0.3
numba==0.43.1
numpy==1.16.2
opencv-python==3.4.2.17
pyparsing==2.3.1
python-dateutil==2.8.0
scikit-learn==0.20.3
scipy==1.2.1
six==1.12.0

Here is the list of the packages that is returned using the "conda list" command
(py370) user@machine:~$ conda list

packages in environment at /data/anaconda/envs/py370:

Name                    Version                   Build  Channel
ca-certificates           2019.1.23                     0  
certifi                   2019.3.9                 py37_0  
cycler                    0.10.0                   pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
imutils                   0.5.2                    pypi_0    pypi
kiwisolver                1.0.1                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libstdcxx-ng              8.2.0                hdf63c60_1  
llvmlite                  0.28.0                   pypi_0    pypi
matplotlib                3.0.3                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1  
numba                     0.43.1                   pypi_0    pypi
numpy                     1.16.2                   pypi_0    pypi
opencv-python             3.4.2.17                 pypi_0    pypi
openssl                   1.0.2r               h7b6447c_0  
pip                       19.0.3                   py37_0  
pyparsing                 2.3.1                    pypi_0    pypi
python                    3.7.0                h6e4f718_3  
python-dateutil           2.8.0                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
scikit-learn              0.20.3                   pypi_0    pypi
scipy                     1.2.1                    pypi_0    pypi
setuptools                40.8.0                   py37_0  
six                       1.12.0                   pypi_0    pypi
sqlite                    3.27.2               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.33.1                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3

**Comment by jwangjie** [comment]
Thank you @guillelopez for sharing your codes.

I have similar issues here. I tested my video with your default weight and yolov3.cfg without any issue. When I am trying to use my own custom trained weights and .cfg files to run your pipeline, the got the same errors. I wonder can you give some instruction about .cfg files, is there anything I need to be careful? 

Best Regards,
Jay

**Comment by guillelopez** [comment]
Yes, I had that same issue with some videos. I guess it's because python arrays have a limit and as the code is recording all the items it founds it's reaching beyond that limit. I guess the code needs to be improved on how it cleans up old references (so the array's size decreases at the same time it keeps growing).

**Comment by bpogorelc** [comment]
Thank you very much for your answer Guille. Your explanation makes a lot of sense.

**Comment by manojbharadhwaj** [comment]
What's the fix for this? @bpogorelc

**Comment by khanhhoangadt** [comment]
Hello. I'm used my data trainning 
labelsPath = os.path.sep.join([args["yolo"], "obj.names"]) #coco.name
LABELS = open(labelsPath).read().strip().split("\n")

# initialize a list of colors to represent each possible class label
np.random.seed(42)
COLORS = np.random.randint(0, 255, size=(200, 3),dtype="uint8")

# derive the paths to the YOLO weights and model configuration 
weightsPath = os.path.sep.join([args["yolo"], "yolov3-tiny-obj_last.weights"])
configPath = os.path.sep.join([args["yolo"], "yolov3-tiny-obj.cfg"])

and runing: python main.py --input input/111.mp4 --output output/1.avi --yolo yolo-coco
[INFO] loading YOLO from disk...
[INFO] 1358 total frames in video
[INFO] single frame took 1.0652 seconds
[INFO] estimated total time to finish: 1446.5812
Traceback (most recent call last):
  File "main.py", line 172, in <module>
    tracks = tracker.update(dets)
  File "E:\phathienxevipham\sort.py", line 203, in update
    trk.update(dets[d,:][0])
IndexError: too many indices for array

**Comment by janstawowy** [comment]
Hi I had the same problem and I've found solution, at least in my case. 
In sort.py class sort method update I've added this at the beginning 
`if len(dets)==0:
     return np.empty((0,5))` 
so the update method now looks like this:
`  def update(self,dets):
    """
    Params:
      dets - a numpy array of detections in the format [[x,y,w,h,score],[x,y,w,h,score],...]
    Requires: this method must be called once for each frame even with empty detections.
    Returns the a similar array, where the last column is the object ID.

    NOTE: The number of objects returned may differ from the number of detections provided.
    """
    #avoid too many indicies error
    if len(dets)==0:
     return np.empty((0,5))
    self.frame_count += 1
    #get predicted locations from existing trackers.
    trks = np.zeros((len(self.trackers),5))
    to_del = []
    ret = []
    for t,trk in enumerate(trks):
      pos = self.trackers[t].predict()[0]
      trk[:] = [pos[0], pos[1], pos[2], pos[3], 0]
      if(np.any(np.isnan(pos))):
        to_del.append(t)
    trks = np.ma.compress_rows(np.ma.masked_invalid(trks))
    for t in reversed(to_del):
      self.trackers.pop(t)
    matched, unmatched_dets, unmatched_trks = associate_detections_to_trackers(dets,trks)
    #update matched trackers with assigned detections
    for t,trk in enumerate(self.trackers):
      if(t not in unmatched_trks):
        d = matched[np.where(matched[:,1]==t)[0],0]
        trk.update(dets[d,:][0])

        print(dets)


    #create and initialise new trackers for unmatched detections
    for i in unmatched_dets:
        trk = KalmanBoxTracker(dets[i,:])
        self.trackers.append(trk)
    i = len(self.trackers)
    for trk in reversed(self.trackers):
        d = trk.get_state()[0]
        if((trk.time_since_update < 1) and (trk.hit_streak >= self.min_hits or self.frame_count <= self.min_hits)):
          ret.append(np.concatenate((d,[trk.id+1])).reshape(1,-1)) # +1 as MOT benchmark requires positive
        i -= 1
        #remove dead tracklet

        if(trk.time_since_update > self.max_age):
          self.trackers.pop(i)



    if(len(ret)>0):
      return np.concatenate(ret)

    return np.empty((0,5))`

Hope it helps.

**Comment by guillelopez** [comment]
Anyone has been able to check if the solution from @janstawowy fixes the issue? If that's the case, if you can do a PR we can add it to the code base.

**Comment by TrinhQuocNguyen** [comment]
> Anyone has been able to check if the solution from @janstawowy fixes the issue? If that's the case, if you can do a PR we can add it to the code base.

I have checked some videos, and it worked!!!

**Comment by bpogorelc** [comment]
I also checked with some videos and it is functioning beautifully!!! Thanks a lot @janstawowi for the solution and @guillelopez for your original project!!!

**Comment by bpogorelc** [comment]
@guillelopez I have made the pull request with the IndexError fix and 2 minor fixes. Feel free to check it and merge it with your master branch if OK

**Comment by guillelopez** [comment]
Ok, it's merged now. Thanks!
