### ISSUE TITLE
these arguments are required.

### ISSUE THREAD

**Issue by Bhuvan-MR** [guillelopez/python-traffic-counter-with-yolo-and-sort#6]
usage: main.py [-h] -i INPUT -o OUTPUT -y YOLO [-c CONFIDENCE] [-t THRESHOLD]
main.py: error: the following arguments are required: -i/--input, -o/--output, -y/--yolo
Can you please fix this?

**Comment by guillelopez** [comment]
Yes, that's what implicitly is specified in the readme file on the 4th step of the "Quick Start" section:
```
$ python main.py --input input/highway.mp4 --output output/highway.avi --yolo yolo-coco
```
