### ISSUE TITLE
Google Colab implementation 

### ISSUE THREAD

**Issue by inteloutside123** [guillelopez/python-traffic-counter-with-yolo-and-sort#8]
Hello Guille, 
very nice work! 
It is possible for you, to transform it into a Google Colab Notebook? 

Other Issue...
I got an Error 

File "/content/python-traffic-counter-with-yolo-and-sort/sort.py", line 23, in <module>
    from filterpy.kalman import KalmanFilter
ModuleNotFoundError: No module named 'filterpy'

Thanks a lot!

**Comment by guillelopez** [comment]
Hi, I will not be transforming it into a Google Colab Notebook. But feel free to do it yourself and share it with everyone. About the error, I guess you need to install filterpy. Check https://filterpy.readthedocs.io/en/latest/.

**Comment by inteloutside123** [comment]
Hi, thanks for your answer! 
Yes, the error came from filterpy. 
I will transform it into a Colab on weekend!
